language: elixir
sudo: false # to use faster container based build environment
elixir:
  - 1.6.1
otp_release:
  - 20.0
matrix:
  include:
    - elixir: 1.9.0
      otp_release: 22.0.4
    - elixir: 1.8.1
      otp_release: 21.3.2
    - elixir: 1.7.4
      otp_release: 21.0
    - elixir: 1.6.1
      otp_release: 20.0
script: mix test --exclude skip_ci
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
services:
  - rabbitmq
